image: jekyll/jekyll

pages:
  script:
  - time jekyll build -s $CI_PROJECT_DIR -d $CI_PROJECT_DIR/public
  - cp $CI_PROJECT_DIR/.well-known $CI_PROJECT_DIR/public
  artifacts:
    paths:
    - public
  only:
  - master
