image: jekyll/jekyll

pages:
  script:
  - time jekyll build -s /builds/dewetblomerus/dewetblomerus.gitlab.io -d /builds/dewetblomerus/dewetblomerus.gitlab.io/public
  artifacts:
    paths:
    - public
  only:
  - master

build_docker:
  script:
  - docker build -t dewet-jekyll .
  only:
  - docker
