image: jekyll/jekyll

pages:
  script:
  - time jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

build_docker:
  script:
  - docker build -t dewet-jekyll .
  only:
  - docker
