image: ruby:2.3

pages:
  script:
  - bundle
  - jekyll build -d public
  artifacts:
    paths:
    - public
  only:
  - master

build_docker:
  script:
  - docker build -t dewet-jekyll .
  only:
  - docker
